#include "HAL/inc/stm32f303xx.h"
#include "HAL/inc/STM32F303xx_GPIO.h"
#include "HAL/inc/STM32F303xx_EXTI.h"

int main()
{
	GPIOE_CLK_ENABLE();
	GPIOA_CLK_ENABLE();
	
	GPIO_InitPin(GPIOE,8,GPIO_MODE_OUTPUT,GPIO_TYPE_PUSHPULL,GPIO_SPEED_HIGH,GPIO_PULL_NONE,0);
	GPIO_InitPin(GPIOE,9,GPIO_MODE_OUTPUT,GPIO_TYPE_PUSHPULL,GPIO_SPEED_HIGH,GPIO_PULL_NONE,0);
	GPIO_InitPin(GPIOA,0,GPIO_MODE_INPUT,GPIO_TYPE_PUSHPULL,GPIO_SPEED_HIGH,GPIO_PULL_NONE,0);

	NVIC_IRQConfig(IRQ_NUM_EXTI0,1,ENABLE);
	EXTI_Init(EXTI_RISING, GPIOA, 0);
	
	while(1);
}

void EXTI0_IRQHandler()
{
	EXTI_Handling(0);
	GPIO_TogglePin(GPIOE, 8);
	for(int i=0; i<400000; i++);
}
